security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Service\Auth\AuthService
            logout:
                path: app_logout
    access_control:
