version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - './docker/data/mysql:/var/lib/mysql'
      - './docker/dump/:/var/dump'
  nginx:
    image: 'nginx:latest'
    volumes:
      - './docker/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './:/var/www/html:rw,delegated'
    ports:
      - '80:80'
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/var/www/html:rw,delegated'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'