version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './dump/:/var/dump'
  nginx:
    image: 'nginx:latest'
    volumes:
      - './config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - '../:/var/www/html:rw,delegated'
    ports:
      - '${LOCALHOST_PORT}:80'
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - '../:/var/www/html:rw,delegated'
    environment:
      PHP_IDE_CONFIG: 'serverName=${PHPSTORM_SERVER_NAME}'
      XDEBUG_CONFIG: 'remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT}'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'